checks if service starts

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -57,6 +57,12 @@ jobs:
                 echo "Error restarting pybackend service."
                 exit 1
             fi
+            echo "Checking service status..."
+            sudo systemctl is-active --quiet pybackend.service
+            if [ $? -ne 0 ]; then
+                echo "Service failed to start."
+                exit 1
+            fi
             echo "Deployment successful and application restarted!"
             ENDSSH
 workflows:
